@startuml
class Preamble << (S,PaleGreen) >> {
    + Preamble()
    + ~Preamble()
    + void add(unsigned int code)
    + string getCode()
    + unordered_map<unsigned int, string> code
    + vector<string> codes 
}

enum CODES {
    Siunitx
    ToDoList
    Biblatex
}

Preamble *- CODES : use
@enduml